"use client";

import Link from "next/link";
import { ArrowLeft, Blend } from "lucide-react";
import { useLangStore } from "@/lib/store/lang-store";

const translations = {
  en: {
    back: "Home",
    title: "Terms of Service",
    lastUpdated: "Last updated: March 24, 2026",

    intro:
      'These Terms of Service ("Terms") govern your access to and use of Meld ("we", "our", or "the Service"), a design-to-code platform. By using the Service, you agree to be bound by these Terms.',

    s1Title: "1. Acceptance of Terms",
    s1Body:
      "By accessing or using Meld, you confirm that you are at least 13 years of age and have the legal capacity to enter into these Terms. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.",

    s2Title: "2. Description of Service",
    s2Body:
      "Meld is a platform that connects Figma designs to your existing codebase. The Service provides AI-powered code modification, design-to-code mapping, and collaborative development tools. We offer Cloud, Local, and Sandbox modes for different workflows.",

    s3Title: "3. Account and Authentication",
    s3Body:
      "You authenticate through GitHub OAuth. You are responsible for maintaining the security of your account credentials. You must not share your account or allow unauthorized access. We only access your public GitHub information unless you explicitly grant additional permissions.",

    s4Title: "4. Acceptable Use",
    s4Items: [
      "You may use the Service only for lawful purposes and in accordance with these Terms.",
      "You must not use the Service to generate malicious code, circumvent security measures, or violate intellectual property rights.",
      "You must not attempt to reverse-engineer, disassemble, or decompile any part of the Service.",
      "You must not use automated means to access the Service beyond what we provide (API, CLI agent).",
    ],

    s5Title: "5. Intellectual Property",
    s5Body:
      "You retain all rights to your code and designs. Code modifications generated by AI through the Service are considered derivative works of your original code, and you own those modifications. Meld retains ownership of the Service, its features, and proprietary technology.",

    s6Title: "6. AI-Generated Content",
    s6Body:
      "The Service uses third-party AI models (Claude, GPT-4o, Gemini) to generate code modifications. AI-generated code is provided as-is. You are responsible for reviewing, testing, and validating all AI-generated code before deploying to production. We do not guarantee the correctness, security, or fitness of AI outputs.",

    s7Title: "7. Data and Privacy",
    s7Body:
      "Your use of the Service is also governed by our Privacy Policy. In Local and Desktop modes, your code is processed on your machine and is not stored on our servers. In Cloud mode, code snippets may be temporarily transmitted to AI providers for processing.",

    s8Title: "8. Service Availability",
    s8Body:
      "We strive for high availability but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to maintenance, updates, or circumstances beyond our control. We are not liable for any loss or damage arising from service interruptions.",

    s9Title: "9. Subscription and Billing",
    s9Body:
      "Free tier users are subject to usage limits. Pro subscriptions are billed monthly or annually as selected. You may cancel at any time, and your subscription will remain active until the end of the current billing period. Refunds are governed by our Refund Policy.",

    s10Title: "10. Limitation of Liability",
    s10Body:
      "To the maximum extent permitted by law, Meld shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the Service.",

    s11Title: "11. Termination",
    s11Body:
      "We may suspend or terminate your access to the Service at any time for violation of these Terms or any other reason. Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination shall survive.",

    s12Title: "12. Changes to Terms",
    s12Body:
      "We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on this page with a new effective date. Your continued use of the Service after such changes constitutes acceptance of the revised Terms.",

    s13Title: "13. Contact",
    s13Body: "If you have questions about these Terms, please contact us at:",
    s13Email: "support@meld.dev",
  },
  ko: {
    back: "홈",
    title: "서비스 이용약관",
    lastUpdated: "최종 업데이트: 2026년 3월 24일",

    intro:
      "본 서비스 이용약관(\"약관\")은 디자인-투-코드 플랫폼인 Meld(\"당사\" 또는 \"서비스\")에 대한 접근 및 사용을 규율합니다. 서비스를 사용함으로써 본 약관에 동의하게 됩니다.",

    s1Title: "1. 약관 동의",
    s1Body:
      "Meld에 접근하거나 사용함으로써 귀하는 만 13세 이상이며 본 약관에 동의할 법적 능력이 있음을 확인합니다. 조직을 대신하여 서비스를 사용하는 경우, 해당 조직을 본 약관에 구속시킬 권한이 있음을 보증합니다.",

    s2Title: "2. 서비스 설명",
    s2Body:
      "Meld는 Figma 디자인을 기존 코드베이스와 연결하는 플랫폼입니다. AI 기반 코드 수정, 디자인-코드 매핑, 협업 개발 도구를 제공합니다. 다양한 워크플로우를 위한 Cloud, Local, Sandbox 모드를 제공합니다.",

    s3Title: "3. 계정 및 인증",
    s3Body:
      "GitHub OAuth를 통해 인증합니다. 계정 자격 증명의 보안을 유지할 책임은 귀하에게 있습니다. 계정을 공유하거나 무단 접근을 허용해서는 안 됩니다. 귀하가 명시적으로 추가 권한을 부여하지 않는 한 공개된 GitHub 정보만 접근합니다.",

    s4Title: "4. 허용되는 사용",
    s4Items: [
      "합법적인 목적으로만, 본 약관에 따라 서비스를 사용할 수 있습니다.",
      "악성 코드 생성, 보안 조치 우회 또는 지적재산권 침해를 위해 서비스를 사용해서는 안 됩니다.",
      "서비스의 일부를 역설계, 분해 또는 디컴파일하려고 시도해서는 안 됩니다.",
      "당사가 제공하는 수단(API, CLI 에이전트) 이외의 자동화된 방법으로 서비스에 접근해서는 안 됩니다.",
    ],

    s5Title: "5. 지적재산권",
    s5Body:
      "귀하의 코드와 디자인에 대한 모든 권리는 귀하에게 있습니다. 서비스를 통해 AI가 생성한 코드 수정은 원본 코드의 파생 저작물로 간주되며, 해당 수정의 소유권은 귀하에게 있습니다. Meld는 서비스, 기능 및 독점 기술의 소유권을 보유합니다.",

    s6Title: "6. AI 생성 콘텐츠",
    s6Body:
      "서비스는 코드 수정을 위해 서드파티 AI 모델(Claude, GPT-4o, Gemini)을 사용합니다. AI 생성 코드는 있는 그대로 제공됩니다. 프로덕션에 배포하기 전에 모든 AI 생성 코드를 검토, 테스트 및 검증할 책임은 귀하에게 있습니다. AI 출력의 정확성, 보안 또는 적합성을 보장하지 않습니다.",

    s7Title: "7. 데이터 및 개인정보",
    s7Body:
      "서비스 사용은 당사 개인정보처리방침의 적용을 받습니다. Local 및 Desktop 모드에서는 코드가 귀하의 기기에서 처리되며 당사 서버에 저장되지 않습니다. Cloud 모드에서는 처리를 위해 코드 스니펫이 일시적으로 AI 공급자에게 전송될 수 있습니다.",

    s8Title: "8. 서비스 가용성",
    s8Body:
      "높은 가용성을 위해 노력하지만 중단 없는 접근을 보장하지는 않습니다. 유지보수, 업데이트 또는 당사가 통제할 수 없는 상황으로 인해 서비스가 일시적으로 사용 불가능할 수 있습니다. 서비스 중단으로 인한 손실이나 피해에 대해 당사는 책임을 지지 않습니다.",

    s9Title: "9. 구독 및 결제",
    s9Body:
      "무료 사용자는 사용량 제한이 적용됩니다. Pro 구독은 선택한 대로 월간 또는 연간으로 청구됩니다. 언제든지 취소할 수 있으며, 현재 결제 기간이 끝날 때까지 구독이 유지됩니다. 환불은 당사 환불 정책에 따릅니다.",

    s10Title: "10. 책임 제한",
    s10Body:
      "법이 허용하는 최대 범위 내에서, Meld는 서비스 사용으로 인한 간접적, 부수적, 특별, 결과적 또는 징벌적 손해, 또는 직접적이든 간접적이든 이익이나 수익의 손실, 데이터, 사용, 신용 또는 기타 무형 손실에 대해 책임을 지지 않습니다.",

    s11Title: "11. 해지",
    s11Body:
      "본 약관 위반 또는 기타 사유로 언제든지 서비스 접근을 일시 중지하거나 해지할 수 있습니다. 해지 시 서비스 사용 권리가 즉시 소멸됩니다. 본질적으로 해지 후에도 존속해야 하는 조항은 존속합니다.",

    s12Title: "12. 약관 변경",
    s12Body:
      "수시로 본 약관을 업데이트할 수 있습니다. 중요한 변경 사항은 새로운 적용 날짜와 함께 이 페이지에 게시하여 알려드립니다. 변경 후 서비스를 계속 사용하면 수정된 약관에 동의하는 것으로 간주됩니다.",

    s13Title: "13. 문의",
    s13Body: "본 약관에 대한 질문이 있으시면 아래로 연락해 주세요:",
    s13Email: "support@meld.dev",
  },
} as const;

export default function TermsPage() {
  const { lang, toggleLang } = useLangStore();
  const t = translations[lang];

  return (
    <div className="min-h-screen bg-white">
      {/* 헤더 */}
      <header className="border-b border-[#F0F0EE]">
        <div className="mx-auto flex max-w-3xl items-center gap-3 px-6 py-4">
          <Link
            href="/"
            className="flex items-center gap-2 text-[13px] text-[#B4B4B0] transition-colors hover:text-[#1A1A1A]"
          >
            <ArrowLeft className="h-3.5 w-3.5" />
            {t.back}
          </Link>
          <div className="flex-1" />
          <div className="flex h-6 w-6 items-center justify-center rounded bg-[#1A1A1A]">
            <Blend className="h-3 w-3 text-white" />
          </div>
        </div>
      </header>

      {/* 본문 */}
      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-[28px] font-bold tracking-[-0.02em] text-[#1A1A1A]">
          {t.title}
        </h1>
        <p className="mt-2 text-[13px] text-[#B4B4B0]">{t.lastUpdated}</p>

        <div className="mt-8 space-y-8 text-[14px] leading-relaxed text-[#555]">
          <p>{t.intro}</p>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s1Title}</h2>
            <p className="mt-2">{t.s1Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s2Title}</h2>
            <p className="mt-2">{t.s2Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s3Title}</h2>
            <p className="mt-2">{t.s3Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s4Title}</h2>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              {t.s4Items.map((item, i) => (
                <li key={i}>{item}</li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s5Title}</h2>
            <p className="mt-2">{t.s5Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s6Title}</h2>
            <p className="mt-2">{t.s6Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s7Title}</h2>
            <p className="mt-2">{t.s7Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s8Title}</h2>
            <p className="mt-2">{t.s8Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s9Title}</h2>
            <p className="mt-2">{t.s9Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s10Title}</h2>
            <p className="mt-2">{t.s10Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s11Title}</h2>
            <p className="mt-2">{t.s11Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s12Title}</h2>
            <p className="mt-2">{t.s12Body}</p>
          </section>

          <section>
            <h2 className="text-[16px] font-semibold text-[#1A1A1A]">{t.s13Title}</h2>
            <p className="mt-2">{t.s13Body}</p>
            <a
              href={`mailto:${t.s13Email}`}
              className="mt-1 inline-block text-[#2E86C1] underline underline-offset-2"
            >
              {t.s13Email}
            </a>
          </section>
        </div>
      </main>

      {/* 푸터 */}
      <footer className="border-t border-[#F0F0EE]">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-6">
          <div className="flex items-center gap-4 text-[12px] text-[#B4B4B0]">
            <Link href="/privacy" className="hover:text-[#787774]">
              {lang === "ko" ? "개인정보처리방침" : "Privacy Policy"}
            </Link>
            <Link href="/refund" className="hover:text-[#787774]">
              {lang === "ko" ? "환불 정책" : "Refund Policy"}
            </Link>
          </div>
          <span className="text-[11px] text-[#D4D4D0]">© 2026 Meld</span>
        </div>
      </footer>

      {/* 언어 토글 */}
      <button
        onClick={toggleLang}
        className="fixed bottom-6 right-6 z-50 flex h-10 w-10 items-center justify-center rounded-full bg-[#1A1A1A] text-[12px] font-semibold text-white shadow-lg transition-all hover:scale-105 active:scale-95"
      >
        {lang === "en" ? "KO" : "EN"}
      </button>
    </div>
  );
}
